fix: 🐛 make sure release version is valid

diff --git a/.github/workflows/update-formulae.yml b/.github/workflows/update-formulae.yml
--- a/.github/workflows/update-formulae.yml
+++ b/.github/workflows/update-formulae.yml
@@ -34,6 +34,10 @@ jobs:
             echo "Unable to find omni version from the JSON"
             exit 1
           fi
+          if ! echo "$OMNI_VERSION" | grep -qiE "^v[0-9]+\.[0-9]+\.[0-9]+(\-[a-z1-9][a-z0-9_-]*)?$"; then
+            echo "Invalid release version: $OMNI_VERSION"
+            exit 1
+          fi
           echo "OMNI_VERSION=v${OMNI_VERSION}" | tee -a "$GITHUB_ENV"
 
       - uses: stefanzweifel/git-auto-commit-action@v4
